version: '3'

services:
  redis:
    image: redis
    ports:
    - 6379:6379
    networks:
      mynetwork:

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - 5555:5555
    depends_on:
      - redis
    networks:
      mynetwork:

      
  database:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data-admin:/var/lib/mysql
    env_file:
      - .env
    networks:
      mynetwork:

networks:
  mynetwork:

volumes:
  data-admin:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/crawler
